[package]
name = "robot"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
rppal = "0.14"
serde = { version = "1", features = ["derive"]}
tracing = "0.1"
tracing-subscriber = "0.3"
crossbeam = "0.8"
common = { path = "../common" }
networking = { path = "../networking" }
bitflags = "1"
paste = "1.0"
fxhash = "0.2"

sysinfo = { version = "0.28", default-features = false }
