[package]
name = "net"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "2.0.0-rc.1"
serde = { version = "1.0", features = ["derive"] }
mio = "0.8"
flate2 = "1.0"
bytes = "1"
